# =====================================================================
# DigitalOcean App Platform Specification
# Using Dockerfile for reliable monorepo builds
# =====================================================================

name: controlbox

# Region - choose closest to your users
region: nyc

# Environment variables shared across services
envs:
  - key: NODE_ENV
    value: production

services:
  # Backend API Server (using Dockerfile)
  - name: api
    github:
      repo: SingSongScreamAlong/ControlBox
      branch: main
      deploy_on_push: true
    # Use Dockerfile with target stage
    dockerfile_path: Dockerfile
    docker_target: server
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/mo - upgrade as needed
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DISCORD_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET

  # Frontend Dashboard (using Dockerfile)
  - name: dashboard
    github:
      repo: SingSongScreamAlong/ControlBox
      branch: main
      deploy_on_push: true
    # Use Dockerfile with dashboard target
    dockerfile_path: Dockerfile
    docker_target: dashboard
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${api.PUBLIC_URL}

# Managed Database (optional - can use external)
databases:
  - name: controlbox-db
    engine: PG
    version: "15"
    size: db-s-dev-database  # $7/mo - smallest
    num_nodes: 1
