# =====================================================================
# DigitalOcean App Platform Specification
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/
# =====================================================================

name: controlbox

# Region - choose closest to your users
region: nyc

# Environment variables shared across services
envs:
  - key: NODE_ENV
    value: production

services:
  # Backend API Server
  - name: api
    github:
      repo: SingSongScreamAlong/ControlBox
      branch: main
      deploy_on_push: true
    # Use Node.js buildpack with explicit build commands
    environment_slug: node-js
    build_command: npm install && npm run build --workspaces
    run_command: node packages/server/dist/index.js
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/mo - upgrade as needed
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DISCORD_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET

  # Frontend Dashboard (static site)
  - name: dashboard
    github:
      repo: SingSongScreamAlong/ControlBox
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build --workspaces
    environment_slug: node-js
    # Build from root to get all files, output from dashboard dist
    output_dir: packages/dashboard/dist
    index_document: index.html
    error_document: index.html  # SPA fallback
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: ${api.PUBLIC_URL}

# Managed Database (optional - can use external)
databases:
  - name: controlbox-db
    engine: PG
    version: "15"
    size: db-s-dev-database  # $7/mo - smallest
    num_nodes: 1
